src/pms/routes/balance.py
import json

from flask import Blueprint, Response, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from pms.authorization import get_user_by_email
from pms.db import get_cursor
from pms.routes.main import join_session_logic

bp = Blueprint("balance", __name__)


def get_transactions_by_user_id(user_id: str) -> list[dict]:
    cursor = get_cursor()
    cursor.execute(
        """
        SELECT *
        FROM pms_transaction
        WHERE user_id = %s
        """,
        (user_id,),
    )
    transactions = cursor.fetchall()
    return transactions


@bp.route("/balance", methods=["GET"])
@bp.route("/balance/<error>", methods=["GET"])
@login_required
def balance(error: str | None = None, swimming_session: dict | None = None):
    user_info = get_user_by_email(current_user.id)

    transactions = get_transactions_by_user_id(current_user.id)

    return render_template(
        "balance.html",
        balance=user_info["balance"] if user_info else 0,
        error=error,
        swimming_session=swimming_session,
        transactions=transactions,
    )


@bp.route(
    "/balance/cart",
    methods=["POST"],
)
@login_required
def cart():
    req = json.loads(request.data) if request.data else request.form
    session_name = req.get("session_name", "")
    session_date = req.get("session_date", "")
    session_start_hour = req.get("start_hour", "")
    session_end_hour = req.get("end_hour", "")

    user_info = get_user_by_email(current_user.id)

    cursor = get_cursor()
    cursor.execute(
        """
        SELECT *
        FROM swimming_session
        WHERE session_name = %s
            AND session_date = %s
            AND start_hour = %s
            AND end_hour = %s
        """,
        (session_name, session_date, session_start_hour, session_end_hour),
    )
    swimming_session = cursor.fetchone()

    transactions = get_transactions_by_user_id(current_user.id)

    return render_template(
        "balance.html",
        balance=user_info["balance"],
        swimming_session=swimming_session,
        transactions=transactions,
    )


@bp.route("/balance/buy", methods=["POST"])
@login_required
def buy():
    req = request.form
    session_name = req.get("session_name", "")
    session_date = req.get("session_date", "")
    session_start_hour = req.get("start_hour", "")
    session_end_hour = req.get("end_hour", "")

    cursor = get_cursor()
    cursor.execute(
        """
        INSERT INTO pms_transaction (
            user_id,
            session_name,
            session_date,
            start_hour,
            end_hour
        ) VALUES (%s, %s, %s, %s, %s)
        """,
        (
            current_user.id,
            session_name,
            session_date,
            session_start_hour,
            session_end_hour,
        ),
    )
    cursor.connection.commit()

    ret = join_session_logic(
        session_name,
        session_date,
        session_start_hour,
        session_end_hour,
        current_user.id,
    )

    if len(ret) > 1:
        print(ret[0])
        return redirect(url_for("balance.balance", error=ret[0]))
    else:
        return Response(status=200)


@bp.route("/balance/add", methods=["POST"])
@login_required
def add_balance():
    amount = 0
    try:
        if not request.form.get("amount"):
            raise ValueError("Amount is required")
        amount = float(request.form["amount"])
    except ValueError:
        return redirect(url_for("balance.balance", error="Added amount is not valid"))

    user_info = get_user_by_email(current_user.id)

    cursor = get_cursor()
    cursor.execute(
        "UPDATE pms_user SET balance = %s + %s WHERE email = %s",
        (amount, user_info["balance"], current_user.id),
    )
    cursor.connection.commit()  # Do not forget to commit updates

    return redirect(url_for("balance.balance"))

src/pms/routes/filters.py
from flask import Blueprint, render_template, request
from flask_login import current_user, login_required

from pms.db import get_cursor  # TODO: Implement database connection

bp = Blueprint("filters", __name__)


@bp.route("/filter_sessions", methods=["GET", "POST"])
@login_required
def filter_sessions():
    results = ["a", "b", "c", "d"]
    status = "get_result"
    cur = get_cursor()
    cur.execute("SELECT username FROM pms_user NATURAL JOIN coach", ())
    coach_results = cur.fetchall()
    cur.execute("SELECT pool_id, pool_city, pool_name FROM pool")
    location_results = cur.fetchall()
    if request.method == "POST":
        data = request.form
        class_type_dict = {
            "Individual": "individual_session",
            "One-to-One": "one_to_one_session",
            "Class": "class_session",
            "Race": "race",
        }
        query_attributes = ["pool_id", "session_date", "start_hour", "end_hour"]
        secondary_attributes = [
            "class_type",
            "instructor",
        ]
        selected_values = {}
        status = "filter_result"
        nonempty_params = []
        session_params = []
        class_type_mapping = {
            "Individual": ["number_of_months"],
            "Class": ["class_level", "signup_date"],
            "Race": ["stroke_style"],
        }
        user_class_params = []
        init_filter_params(
            data,
            query_attributes,
            secondary_attributes,
            nonempty_params,
            selected_values,
            class_type_mapping,
            session_params,
            user_class_params,
        )
        cur = get_cursor()
        age_query = """SELECT EXTRACT(YEAR FROM AGE(birth_date)) AS age
                        FROM pms_user
                        WHERE email = %s;
        """
        cur.execute(age_query, (current_user.id,))
        age_result = cur.fetchone()["age"]
        print(age_result)
        session_query = ""
        session_params_operators = {
            "signup_date": ">=",
            "class_level": "=",
            "age_group": "=",
            "stroke_style": "=",
            "number_of_months": "=",
        }
        for i in range(0, len(session_params)):
            selected_values[session_params[i]] = data[session_params[i]]
            session_query += "{session_params} {operator} %s AND ".format(
                session_params=session_params[i],
                operator=session_params_operators[session_params[i]],
            )
        user_params_operators = {"min_age": "<=", "max_age": ">="}
        for i in user_class_params:
            session_query += "{user_param} {operator} %s AND ".format(
                user_param=i,
                operator=user_params_operators[i],
            )
        session_query = session_query[:-5]

        query = """WITH first_filter AS (
                    SELECT session_name, session_date, start_hour, end_hour, price
                    FROM swimming_session
                    JOIN coach ON swimming_session.coach_email=coach.email
                    NATURAL JOIN booking NATURAL JOIN pool
                """
        if len(nonempty_params) > 0:
            query += "WHERE "
        else:
            query += ")"
        query_operators = {
            "pool_id": "=",
            "session_date": "=",
            "start_hour": ">=",
            "end_hour": "<=",
        }
        for i in range(0, len(nonempty_params)):
            selected_values.update({nonempty_params[i]: data[nonempty_params[i]]})
            subq = "{x} {operator} %s AND ".format(
                x=nonempty_params[i], operator=query_operators[nonempty_params[i]]
            )
            query += subq
        query = query[:-5] + ")"
        query += (
            "\nSELECT DISTINCT * FROM {dict_entry} NATURAL JOIN first_filter\n".format(
                dict_entry=class_type_dict[data["class_type"]]
            )
        )
        if len(session_query) + len(user_class_params) > 0:
            query += "WHERE "
        query += session_query
        print(query)
        total_list = []
        for i in nonempty_params:
            total_list.append(data[i])
        for i in session_params:
            total_list.append(data[i])
        if len(user_class_params) > 0:
            total_list.append(age_result)
            total_list.append(age_result)
        total_tuple = tuple(total_list)
        print(total_tuple)
        cur.execute(query, total_tuple)
        results = cur.fetchall()
        return render_template(
            "filter/filter.html",
            selected_values=selected_values,
            results=results,
            len=len(results),
            status=status,
            coach_results=coach_results,
            coach_len=len(coach_results),
            location_results=location_results,
            location_results_len=len(location_results),
        )
    return render_template(
        "filter/filter.html",
        results=results,
        len=len(results),
        status=status,
        coach_results=coach_results,
        coach_len=len(coach_results),
        location_results=location_results,
        location_results_len=len(location_results),
    )


def init_filter_params(
    data,
    query_attributes,
    secondary_attributes,
    nonempty_params,
    selected_values,
    class_type_mapping,
    session_params,
    user_class_params,
):
    for key, value in data.items():
        if value and (key in query_attributes):
            nonempty_params.append(key)
        elif value and (key in secondary_attributes):
            selected_values[key] = value
        elif (
            value
            and data["class_type"]
            and key in class_type_mapping[data["class_type"]]
        ):
            session_params.append(key)
    if data["class_type"] == "Class" or data["class_type"] == "Race":
        user_class_params.append("min_age")
        user_class_params.append("max_age")


@bp.route("/view_session", methods=["POST"])
@login_required
def session_info():
    results = []
    cur = get_cursor()
    data = request.form
    reason = ""

    existence_query = """SELECT *
                FROM swimmer_attend_session S
                WHERE S.email = %s AND
                S.session_date = %s AND
                (S.start_hour <= %s OR S.end_hour >= %s);"""
    cur.execute(
        existence_query,
        (
            current_user.id,
            data["session_date"],
            data["start_hour"],
            data["end_hour"],
        ),
    )
    isExists = cur.fetchone()
    if isExists:
        reason = "Course conflict"
    cost_query = """ SELECT balance, price
                FROM pms_user P, swimming_session S
                WHERE P.email = %s AND
                S.session_name = %s AND
                S.session_date = %s AND
                S.start_hour = %s AND
                S.end_hour = %s;
                """
    cur.execute(
        cost_query,
        (
            current_user.id,
            data["session_name"],
            data["session_date"],
            data["start_hour"],
            data["end_hour"],
        ),
    )
    cost_json = cur.fetchone()
    balance = cost_json["balance"]
    price = cost_json["price"]
    if balance < price:
        reason = "Balance not enough"

    date_query = """SELECT * FROM swimming_session S
                    WHERE S.session_name = %s AND
                    S.session_date = %s AND S.start_hour = %s
                    AND S.end_hour = %s AND
                    S.session_date < CURRENT_DATE OR
                    (S.session_date = CURRENT_DATE AND S.start_hour < CURRENT_TIME);
    """
    cur.execute(
        date_query,
        (
            data["session_name"],
            data["session_date"],
            data["start_hour"],
            data["end_hour"],
        ),
    )
    date_result = cur.fetchone()
    if date_result:
        reason = "Session no longer available"

    signup_date_query = """SELECT * FROM swimming_session S
                    NATURAL JOIN class_session C
                    WHERE S.session_name = %s AND
                    S.session_date = %s AND S.start_hour = %s
                    AND S.end_hour = %s AND
                    C.signup_date < CURRENT_DATE;
    """
    cur.execute(
        signup_date_query,
        (
            data["session_name"],
            data["session_date"],
            data["start_hour"],
            data["end_hour"],
        ),
    )
    signup_date_result = cur.fetchone()
    if signup_date_result:
        reason = "Signup deadline is passed"

    class_type_dict = {
        "Individual": "individual_session",
        "One-to-One": "one_to_one_session",
        "Class": "class_session",
        "Race": "race",
    }

    query = """SELECT *
                FROM swimming_session S
                NATURAL JOIN {dict_entry}
                WHERE S.session_name = %s AND
                S.session_date = %s AND S.start_hour = %s
                AND S.end_hour = %s;""".format(
        dict_entry=class_type_dict[data["class_type"]]
    )
    cur.execute(
        query,
        (
            data["session_name"],
            data["session_date"],
            data["start_hour"],
            data["end_hour"],
        ),
    )
    results = cur.fetchone()
    if (
        "max_capacity" in results.keys()
        and "number_of_participants" in results.keys()
        and results["max_capacity"]
        and results["number_of_participants"]
        and results["max_capacity"] == results["number_of_participants"]
    ):
        reason = "Class full"

    results["duration"] = (
        (results["end_hour"].hour - results["start_hour"].hour) * 60
        + results["end_hour"].minute
        - results["start_hour"].minute
    )
    label_converter = {}
    l1 = {}
    ignore_list = [
        "min_age",
        "max_age",
    ]  # Without any end_hour no session can be identified
    if (

src/pms/templates/filter/filter.html
<!DOCTYPE html>
<html lang="en">
{% include "head.html" %}

<body class="bg-light">
    <!-- Navigation -->
    {% include "nav.html" %}

    <div class="container my-5">
        <h2 class="text-primary mb-4">Search for Sessions</h2>
        <div class="row">
            <div class="col-md-4">
                <form action="{{ url_for('filters.filter_sessions') }}" method="post" class="p-4 bg-white shadow rounded">
                    <div class="mb-3">
                        <label for="pool_id" class="form-label fw-bold">Location</label>
                        <select id="pool_id" name="pool_id" class="form-select">
                            <option value="">-- select an option --</option>
                            {% if location_results is defined %}
                                {% for i in range(0, location_results_len) %}
                                    <option value="{{ location_results[i].pool_id }}">{{location_results[i].pool_name}} - {{ location_results[i].pool_city }} ({{location_results[i].pool_id}})</option>
                                {% endfor %}
                            {% endif %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="class_type" class="form-label fw-bold">Class Type</label>
                        <select id="class_type" name="class_type" class="form-select">
                            <option value="Race">Race</option>
                            <option value="Class">Class</option>
                            <option value="Individual">Individual</option>
                            <option value="One-to-One">One-to-One</option>
                        </select>
                    </div>

                    <div class="mb-3">
                        <label for="instructor" class="form-label fw-bold">Instructor</label>
                        <select id="instructor" name="instructor" class="form-select">
                            <option value="">-- select an option --</option>
                            {% if coach_results is defined %}
                                {%for i in range(0, coach_len)%}
                                    <option value="{{coach_results[i].username}}">{{coach_results[i].username}}</option>
                                {%endfor%}
                            {% endif %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="session_date" class="form-label fw-bold">Session Date</label>
                        <input type="date"
                        id="session_date"
                        name="session_date"
                        class="form-control"
                        {% if selected_values is defined and selected_values["session_date"] is defined %}
                        value="{{selected_values['session_date']}}"
                        {% endif %}
                        />
                    </div>
                    <div class="mb-3">
                        <label for="start_hour" class="form-label fw-bold">Start Hour</label>
                        <input type="time" id="start_hour" name="start_hour" class="form-control"/>
                    </div>
                    <div class="mb-3">
                        <label for="end_hour" class="form-label fw-bold">End Hour</label>
                        <input type="time" id="end_hour" name="end_hour" class="form-control"/>
                    </div>
                    <div class="mb-3">
                        <label for="number_of_months" class="form-label fw-bold">Number of Months (For indivdual sessions)</label>
                        <input type="number" id="number_of_months" name="number_of_months" class="form-control"/>
                    </div>
                    <div class="mb-3">
                        <label for="class_level" class="form-label fw-bold">Class Level (For class sessions)</label>
                        <select id="class_level" name="class_level" class="form-select">
                            <option value="">-- select an option --</option>
                            <option value="Beginner">Beginner</option>
                            <option value="Intermediate">Intermediate</option>
                            <option value="Advanced">Advanced</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="signup_date" class="form-label fw-bold">Signup Date (For class sessions)</label>
                        <input type="date" id="signup_date" name="signup_date" class="form-control"/>
                    </div>
                    <div class="mb-3">
                        <label for="stroke_style" class="form-label fw-bold">Stroke Style (For race sessions)</label>
                        <select id="stroke_style" name="stroke_style" class="form-select">
                            <option value="">-- select an option --</option>
                            <option value="Freestyle">Freestyle</option>
                            <option value="Backstroke">Backstroke</option>
                            <option value="Butterfly">Butterfly</option>
                        </select>
                    </div>
                    <!-- Add more form fields as needed -->
                    <button type="submit" class="btn btn-primary w-100">Apply</button>
                </form>
            </div>
            <div class="col-md-8">
                <div class="row">
                    {% if status == "filter_result" %}
                        {% for i in range(0, len) %}
                            <div class="col-md-6 mb-3">
                                <form class="p-3 bg-white shadow rounded" action="{{ url_for('filters.session_info') }}" method="post">
                                    <h5 class="fw-bold">Session: {{ results[i].session_name }}</h5>
                                    <p>Date: {{ results[i].session_date }}</p>
                                    <button type="submit" class="btn btn-sm btn-primary w-100">Details</button>
                                    <input type="hidden" name="session_name" value="{{ results[i].session_name }}">
                                    <input type="hidden" name="session_date" value="{{ results[i].session_date }}">
                                    <input type="hidden" name="start_hour" value="{{ results[i].start_hour }}">
                                    <input type="hidden" name="end_hour" value="{{ results[i].end_hour }}">
                                    <input type="hidden" name="class_type" value="{{ selected_values.class_type }}">
                                </form>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    {% include "footer.html" %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

src/pms/templates/filter/session.html
<!DOCTYPE html>
<html lang="en">
{% include "head.html" %}

<body class="bg-light">
    <!-- Navigation -->
    {% include "nav.html" %}
    <!-- Container -->
    <div class="container my-5 vh-100">
        <!-- Class Title -->
        <div class="mb-4">
            <h2>{{results["session_name"]}}</h2>
        </div>

        <!-- Class Details Section -->
        <div class="mb-4">
            <h5 class="text-primary">Class Details</h5>
            <div class="row">
                {%for key, value in results.items():%}
                    <div class="col-md-3">
                        <p class="mb-1 text-secondary fw-bold">{{label_converter[key]}}</p>
                        <p class="text-dark">{{value}}</p>
                    </div>
                {% endfor %}
            </div>
        </div>

        <!-- Action Buttons -->
        <div class="d-flex justify-content-between">
            <form action="{{url_for('filters.filter_sessions')}}">
                <button type="submit" class="btn btn-outline-secondary">Cancel</button>
            </form>
            {% if canBeTaken %}
                <!-- Do not forget to enter payment page url here -->
                <form action="{{ url_for('balance.cart') }}" method="post" >
                    <input type="hidden" name="session_name" value="{{results.session_name}}">
                    <input type="hidden" name="session_date" value="{{results.session_date}}">
                    <input type="hidden" name="start_hour" value="{{results.start_hour}}">
                    <input type="hidden" name="end_hour" value="{{ results.end_hour }}">
                    <button type="submit" class="btn btn-primary">Book</button>
                </form>
            {% else %}
                <span class="text-danger">{{reason}}</span>
            {% endif %}
        </div>
    </div>
    <!-- Footer -->
    {% include "footer.html" %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>